app1/urls.py
from django.urls import path

from app1.views import *

app_name="app1"

urlpatterns=[
    path("one/",one,name="one"),
    path("three/",three,name="three"),
    path('five/',five,name="five"),
    path("seven/",seven,name="seven"),
]

app2/urls.py
from django.urls import path

from app2.views import *

app_name="app2"

urlpatterns=[
    path("two/",two,name="two"),
    path("four/",four,name="four"),
    path('six/',six,name="six"),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from app.views import *
import app1,app2
urlpatterns = [
    path("admin/", admin.site.urls),
    path("app1/",include("app1.urls")),

    
    path("app2/",include("app2.urls")),
    path("registration/",registration,name="registration"),
    path("home/",home,name="home"),
    path('user_login/',user_login,name='user_login'),
    path('user_logout/',user_logout,name='user_logout'),
    path("eight/",eight,name="eight"),
    path("payment/",payment,name="payment"),
    path('display_profile/',display_profile,name='display_profile'),
    path('change_password/',change_password,name='change_password'),
    path('reset_password/',reset_password,name='reset_password'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

app/models.py
from django.db import models
from django.contrib.auth.models import User
class Profile(models.Model):
    username=models.OneToOneField(User,on_delete=models.CASCADE)
    address=models.TextField()
    profile_pic=models.ImageField(upload_to='pp')

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from app.models import *
class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password','email']
        widgets={'password':forms.PasswordInput}
        help_texts={'username':''}
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['address','profile_pic']

app/views.py
from django.shortcuts import render
from app.forms import *
from django.http import HttpResponse
from django.http import HttpResponse,HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse

from django.contrib.auth.decorators import login_required

def home(request):
    if request.session.get('username'):
        username=request.session.get('username')
        d={'username':username}
        return render(request,'home.html',d)
    return render(request,'home.html')

def registration(request):
        UFD=UserForm()
        PFD=ProfileForm()
        d={'UFD':UFD,'PFD':PFD}
        if request.method=='POST' and request.FILES:
              UFD=UserForm(request.POST)
              PFD=ProfileForm(request.POST,request.FILES)
              if UFD.is_valid() and PFD.is_valid():
                NSUO=UFD.save(commit=False)
                password=UFD.cleaned_data['password']
                NSUO.set_password(password)
                NSUO.save()
                NSPO=PFD.save(commit=False)
                NSPO.username=NSUO
                NSPO.save()
                send_mail('Registratioon',
                        "Succefully Registration",
                      'gollavishnuyadav2@gmail.com',
                      [NSUO.email],
                      fail_silently=False
                      )
                return HttpResponse('Registration Success')
              else:
                  return HttpResponse("NOT VALID")
        return render(request,'login.html',d)
def user_login(request):
    if request.method=='POST':
        username=request.POST['un']
        password=request.POST['pw']
        user=authenticate(username=username,password=password)

        if user and user.is_active:
            login(request,user)
            request.session['username']=username
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponse('u r not an authenticated user')
    return render(request,'user_login.html')



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def eight(request):
    return render(request,'eight.html')



def payment(request):
    return render(request,'payment.html')



def reset_password(request):

    if request.method=='POST':
        un=request.POST['un']
        pw=request.POST.get('pw')

        LUO=User.objects.filter(username=un)

        if LUO:
            UO=LUO[0]
            UO.set_password(pw)
            UO.save()
            return HttpResponse('password reset is done')
        else:
            return HttpResponse('Reset password is done successfully')
    return render(request,'reset_password.html')



@login_required
def display_profile(request):
    username=request.session.get('username')
    UO=User.objects.get(username=username)
    PO=Profile.objects.get(username=UO)
    d={'UO':UO,'PO':PO}
    return render(request,'profile_display.html',d)

@login_required
def change_password(request):
    if request.method=='POST':
        pw=request.POST['password']
        username=request.session.get('username')
        UO=User.objects.get(username=username)
        UO.set_password(pw)
        UO.save()
        return HttpResponse('Password is changed successfully')
    return render(request,'change_password.html')


def reset_password(request):
    if request.method=="POST":
        un=request.POST['un']
        pw=request.POST['pw']
        LUO=User.objects.filter(username=un)
        if LUO:
            LUO[0].set_password(pw)
            LUO[0].save()
        else:
            return HttpResponse('Not Done')
    return render(request,'reset_password.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request,"one.html")

def three(request):
    return render(request,"home.html")

def five(request):
    return render(request,"five.html")

def seven(request):
    return render(request,"seven.html")

app2/views.py
from django.shortcuts import render

# Create your views here.
def two(request):
    return render(request,"two.html")

def four(request):
    return render(request,"four.html")

def six(request):
    return render(request,"six.html")

templates/change_password.html
{% extends 'dummy.html' %}

{% block title %}
    <title>Home Page</title>

{% endblock %}


{% block body_block %}
    
<style>
    .card
{
    
    width:300px;
    height: 300px;
    margin-top:200px;
    margin-left: -130px;
    border-top-right-radius: 50%;
    border-bottom-left-radius: 50%;
    background-color: rgb(59, 102, 17);
    
}
.card:hover
{
    box-shadow: rgba(240, 46, 170, 0.4) 5px 5px, rgba(240, 46, 170, 0.3) 10px 10px, rgba(240, 46, 170, 0.2) 15px 15px, rgba(240, 46, 170, 0.1) 20px 20px, rgba(240, 46, 170, 0.05) 25px 25px 25px;
    cursor: pointer;
    box-shadow: 
   0 0 0 1px green, /* thin green border */
   0 2px 2px rgba(0,0,0,0.2), /* soft black drop shadow */
   1px 1px 1px rgba(0,0,0,0.2), /* offset the top-right corner */
   -1px -1px 1px rgba(0,0,0,0.2), /* and the bottom-left corner */
   0 0 2px rgba(60, 163, 15, 0.2) /* add a bit more shadow to the whole thing */

}
.input,input
{
    border: none;
    width: 150px;
    padding: 10px;
    margin-top: 10px;
    margin-left: 10px;
    border-top-right-radius: 50%;
    border-bottom-left-radius: 50%;
    box-shadow: 10px 10px 5px 12px lightblue
    
}
body
{
    background-image: url("");
    background-repeat: no-repeat;
    background-size: cover;
    margin-right:150px;

}

</style>
    <form method="POST">
        {% csrf_token %}
        
        <div class="card">
        <label for="password">password</label>
        <input type="password" name="password" id="password">
        <br>
        <br><input type="submit" value="change_password" class="btn btn-danger">
        </div>

    </form>

{% endblock %}

templates/dummy.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
      .nav
      {
        background-color: blue;
        color: white;
        font-weight: bold;
        width: 1900px;
        font-family: Arial, Helvetica, sans-serif;
      }
      .nav>a
		{
			color: rgb(255, 244, 244);
			font-size: medium;
			font-weight: bold;
		}
    </style>
{% block title %}
    <title>Hello, world!</title>
{% endblock %}
  </head>
  <body>

<center>
    <nav class="nav";>
        <a href="{% url 'admin:index' %}" class="nav-link">ADMIN</a>
        <a href="{% url 'registration' %}" class="nav-link">REGISTER</a>
        <a href="{% url 'app1:three' %}" class="nav-link">HOME PAGE</a>
  
     
        {% if user.is_authenticated %}
      
        <a href="{% url 'change_password' %}" class="nav-link">CHANGE PASSWORD</a>
        <a href="{% url 'user_logout' %}" class="nav-link">LOGOUT</a>
      
      {% else %} 
      <a href="{% url 'user_login' %}" class="nav-link">LOGIN</a>
      {% endif %}
    
    </nav>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
{% block body_block %}
{% endblock %}

</center>
  </body>
</html>

templates/four.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src="https://kit.fontawesome.com/e681d559bc.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e681d559bc.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<style>
		*
		{
			margin: 0px; 
		}
		.card
		{
			justify-content: space-around;
			align-items: center;
			display: flex;
			flex-direction: row;
			height: 50px;
		      color: white;
		      background-color: black;
		      font-weight: bold;
		      width: 100vw;
		      font-size: larger;
		      flood-color: rgb(255, 255, 255);
		      border-radius: 0%;
		      transition: all 0s linear 1s;
     

		}
        a:hover
        {
            color: rgb(190, 2, 2);
            box-shadow:0 0 10 rgb(76, 42, 42);
            border-top-right-radius: 50px;
            border-bottom-left-radius: 50px;
            
        }
		a
		{
			margin-left: 20px;
		}
        input
        {
            width: 600px;
            box-shadow: ;
        }
        .a
        {
            border-radius: 100px;
			

        }
        aside
        {
        	height: 100vh;
        	float: left;
        }
        article
        {
        	justify-content: center;
        	align-items: center;
        	display: flex;
        	flex-direction: row;
        	float: left;
/*        	margin-top: 100px;*/
        }
        .card2
        {
        	justify-content: space-between;
        	display: flex;
        	flex-direction: row;
        	align-items: center;
        	background-color: whitesmoke;
        	margin: 0px;

        }
        .aa
        {
        	text-align: center;
        	font-size: 30px;

        }
        .aa:hover
        {
        	transition: all 0s linear 1s;
        	transform: perspective(200px) translate3d(10px, 100px, -100px);

        }
        .div
        {
        	height: 100vh;
        	background-color:orange;
        	width: 20vw;
        	margin-top: 700px;
        	margin-left: -1200px;
        	flex-direction: row;
        }
        .div2
        {
        	font-size: 10px;
        	justify-content: right;
        	background-color: ghostwhite;
        	width: 100vw;
        	align-items: center;
        	

        }
        .card3
        {
        	justify-content: space-between;
        	display: flex;
        	flex-direction: row;
        	align-items: center;
        	background-color: whitesmoke;
        	font-size: 15px;
        	font-weight: bold;
        	font-family:sans-serif;
        }
        img
		{
		  transition: transform .2s; 
		}

		img:hover
		{
		  transform: scale(1.5);
		}
		@media (min-width:0px) and (max-width:800px)
        {
            .card
            {
                flex-direction: column;
				display: inline-block;
				height: 110px;
            }
			.card1
			{
				flex-direction: column;
				display: inline-block;
				height: 11px;
			}
        }
		p
		{
			font-size: 10px;
			font-style: italic;
			font-weight:thick;	
		}
		.card1
		{
			justify-content: space-between;
			align-items: center;
			display: flex;
			flex-direction: row;
			background-color:white;
   			height: 120px;
            color: white;
            font-weight: bold;
            flood-color: rgb(255, 255, 255);
            border-radius: 0%;
            transition: all 0s linear 1s;
            font-family:monospace;
            text-decoration: none;
           }
		   .one>img
			{
				text-decoration: none;
				width: 50px;
				border: none;
			}
			.select>select
			{
				background-color: rgb(5, 8, 8);
				color: rgb(255, 254, 250);
				font-size: medium;
				font-weight: bold;
				font-family: Arial, Helvetica, sans-serif;
			}
	</style>
</head>
<body>
	<header>
		<div class="card">
			<div>
				<a href="https://www.flipkart.com/">Flipkart</a>
			</div>
			<div>
				<button class="btn btn-primary"><input type="text" name="" placeholder="search"></button>
			</div>
			<div>
				<a href="{% url 'home' %}"><button class="btn btn-secondary">HOME</button></a>
				<!-- <a href="{% url 'home' %}" class="nav-link">HOME</a> -->
			</div>
			<div>
				<a href="{% url 'payment' %}"><i class="fa-solid fa-indian-rupee-sign"></i></a>
			</div>
			<div class="a">
				 <a href="https://en.wikipedia.org/wiki/Solar_System"></a>
				<button class="btn btn-secondary">
					<div class="select">
					<select>
                    <option>For more information</option></button>
					<option><a href=""><i class="fa-solid fa-bell"></i>Notification Preference</option></a>
					<option>24*7 Customer Support</option>
					<option>Advertise</option>
                    <option>Download</option>
				</select>
			</div></button>
			</div>
			<div>
			
			</div>
		</div>
		
		<div class="card1">
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100">
				<br>
				<a href="">GROCERY&FOOD</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/22fddf3c7da4c4f4.png?q=100">
				<br>
				<a href="">MOBILES</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/69c6589653afdb9a.png?q=100">
				<br>
				<a href="">ELECTRONICS</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/fk-p-flap/128/128/image/d34810848b2895c9.png?q=100">
				<br>
				<a href="">FASHION</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/71050627a56b4693.png?q=100">
				<br>
				<a href="">TRAVELS</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/ab7e2b022a4587dd.jpg?q=100">
				<br>
				<a href="">APPLIANCE</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/0ff199d1bd27eb98.png?q=100">
				<br>
				<a href="">HOME</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/dff3f7adcf3a90c6.png?q=100">
				<br>
				<a href="">TOY</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/flap/128/128/image/f15c02bfeb02d15d.png?q=100">
				<br>
				<a href="">OFFERS</a>
			</div>
			<div class="one">
				<img src="https://rukminim1.flixcart.com/fk-p-flap/128/128/image/05d708653beff580.png?q=100">
				<br>
				<a href="">TWO-WHEELERS</a>
			</div>
		</div>
					<div class="div2">
						<p>A good quality electric men’s shaver makes the shaving experience a pleasant one. Whether it’s trimming facial hair, getting rid of the nose hair, or getting an immaculate clean shave, an electric shaver helps you to do all tasks seamlessly. What’s more? The electric shavers are ideal for those with sensitive skin, and you don’t have to bother about painful razor cuts. Regardless of your tight schedule, an electric shaver and trimmer is the one-stop solution for all your shaving needs. There are different types of electric shavers, such as electric foil shavers, rotatory electric shavers, corded, and cordless shavers. The price of the men’s shavers online can vary depending upon the product variant, brand, and additional features. Brands like Syska, Panasonic, PHILIPS, HAVELLS, Richards n Steven, etc., manufacture top-notch quality electric shavers. Panasonic ES-LV9Q is an excellent choice for both men and women with sensitive skin. Electric men’s shavers come with a set of instructions and the precautions you need to take while shaving. Depending on your shaving requirements, choose from the variety of shavers available online after checking reviews and ratings, and get them delivered to your doorstep easily.</p>
						<div class="card3">
							<li>SORTBY</li>
							<li>POPULARITY</li>
							<li>PRICE</li>
							<li>NEW</li>
							<li>MORE</li>
						</div>
						<br>
						<br>
				<div class="card2">
					<div>
						<img src="https://rukminim1.flixcart.com/image/612/612/koenl3k0/trimmer/e/j/k/0-5-20-mm-stainless-steel-nht-1053-usb-corded-cordless-nova-original-imag2v6ne4uvssh6.jpeg?q=70" width="200px" height="200px">
						<br>
							<p>
							RACCOON Professional Beard Trimmer For Men
							<br>, Durable Sha...</p>
							<p style="color: red;">From Rs.1500</p>
							<p>Phillips</p>
						<br>
						<img src="https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png" width="100px">
					</div>
					<br>
					<div>
						<a href="{% url 'app1:five' %}"><img src="https://rukminim1.flixcart.com/image/416/416/kr2e3680/shaver/l/e/w/gold-series-corded-cordless-shaver-gs-05-groomiist-original-imag4xhsxz5nyczy.jpeg?q=70" width="200px" height="250px"></a>
						<br>
							<p>
							RACCOON Professional Beard Trimmer For Men
							<br>, Durable Sha...</p>
							<p style="color: red;">From Rs.1500</p>
							<p>Phillips</p>
						<br>
						<img src="https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png" width="100px">
					</div> 
					<br>
					<div>
						<img src="https://rukminim1.flixcart.com/image/612/612/xif0q/trimmer/p/r/d/0-5-3-mm-pocket-electric-trimmer-for-men-and-women-stainless-original-imagq4zdzga3rpzx.jpeg?q=70" width="200px">
						<br>
							<p>
							RACCOON Professional Beard Trimmer For Men
							<br>, Durable Sha...</p>
							<p style="color: red;">From Rs.1500</p>
							<p>Phillips</p>
						<br>
						<img src="https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png" width="100px">
					</div>
					<br>
					<div>
						<br>
						<img src="https://rukminim1.flixcart.com/image/612/612/xif0q/trimmer/u/v/w/0-5-12-mm-at-538-h-t-c-professional-beard-trimmer-stainless-original-imaghr4egr5cje7c.jpeg?q=70" width="200px" height="300px">
						<br>
							<p>
							RACCOON Professional Beard Trimmer For Men
							<br>, Durable Sha...</p>
							<p style="color: red;">From Rs.1500</p>
							<p>Phillips</p>							RACCOON Professional Beard Trimmer For Men
							<br>, Durable Sha...</p>
							<p style="color: red;">From Rs.1500</p>
							<p>Phillips</p>
						<br>
						<img src="https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png" width="100px">
					</div> 
					</div>				
          </body>
          </html>
          <link rel="stylesheet" type="text/css" href="">

templates/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/e681d559bc.js" crossorigin="anonymous"></script>
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css"
rel="stylesheet"
/>
<style>
    
    .pay
    {
       
        height: 100vh;
        width: 50vw;
        text-align: center;
        
        width: 600px;
    }
    .element
    {
        background-color: rgb(27, 19, 19);
        padding: 20px;
        color: rgb(31, 170, 221);
        font-size: medium;
        font-family: Georgia, 'Times New Roman', Times, serif;
        font-weight: bold;
        font-style: normal;
        margin-bottom: 10px ;
        border-radius: 0%;
        text-align: center;
        
        
    }
    h1
    {
        margin: 0px;
        width: 600px;
        margin-top: -1px;
        height: 100px;
        background-color: blue;se
    }
    body
    {
        background-image: url("");
        background-repeat: no-repeat;
        background-size: cover;
    }
    button
    {
    
        color: rgb(255, 255, 255);
        margin-left: 8%;
        margin-bottom: 2%;
        transition: all 1s linear 0s ;
        background-color: rgba(5, 0, 5, 0);
        box-shadow: 10px 10px 5px lightblue;
    }
    button:hover
    {
        border-top-right-radius: 50%;
        border-bottom-left-radius: 50%
    }
    </style>
</head>
<body>
<center>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12">
    <div class="car">
        <nav class="nav">
            <button class="btn-black"><a href="{% url 'admin:index' %}" class="nav-link">Admin Page</a></button>
                <button><a href="{% url 'home' %}" class="nav-link">Home Page</a></button>
                <!-- <button> <a href="{% url 'registration' %}" class="nav-link">Registration Page</a></button>
                <button> <a href="{% url 'app1:one' %}" class="nav-link">UNIVERSE MODEL</a></button>
                <button> <a href="{% url 'app2:two' %}" class="nav-link">FLIPKART MODEL</a></button> -->
                </nav>
         <!-- <img src="https://th.bing.com/th/id/R.7af51d493c25d2361a7a7daf5dad209d?rik=5SLngYXjvegzIg&riu=http%3a%2f%2f4.bp.blogspot.com%2f-Ab3cD6Z8T10%2fU8ElPxQ0niI%2fAAAAAAAABPk%2f5hn9haUz4p0%2fs1600%2fflipkart_logo.png&ehk=O9kMtq71sXAGBjJWcYAvkoLYluJ2hIngmibIuS4gngc%3d&risl=&pid=ImgRaw&r=0" class="imgg"> -->
        
    </div>
    <div class="col-sm-12">
        <div class="pay">
           
            <!-- <div class="element">
            PhonePe(UPI,Wallet) <button class="btn btn-success">New</button> <input type="radio" name="a">
            <br>
            <small>By Now Pay After 20 May</small>
            </div>
            <br>
 -->

        <div class="element">
            phonePe(UPI,Wallet) <button><i class="fa-brands fa-cc-amazon-pay"></button></i>            <input type="radio" name="a">
        </div>
        <br>


        <div class="element">
        Credi/Debit/ATM Card<span style="color: red;" >New</span>     <input type="radio" name="a">
        </div>
        <br>


    <!-- <div class="element">
        Net Banking <span style="color: red;" >New</span>     <input type="radio" name="a">
    </div> -->

    <br>
        <div class="element">
        Cash On Delivery<span style="color: red;" >New</span>       <input type="radio" name="a">
    </div>

    <br>
        <!-- <div class="element">
        EMI(Easy Installments)<span style="color: red;" >New</span>     <input type="radio" name="a">
        </div>
        <br>
            <div class="element">
            Gift Card<span style="color: red;" >New</span>                  <input type="radio" name="a">
            </div>
                <br> -->
        <div class="element">
                <h2>PRICE DETAILS</h2>
                <p>Rs.119</p>
                <small style="color:rgb(43, 43, 232);">View Price Details</small>
                <br>
                <button class="btn btn-danger">CONTINUE</button>
            </div>
            <br>
        </div>
    </div>
    </div>
    </div>
    </div>
    </center>

</body>
</html>

templates/profile_display.html
{% extends 'dummy.html' %}

{% block title %}
    <title>Profile Page</title>

{% endblock %}


{% block body_block %}
    <h1>Details of the user are</h1>

    <h2>name is {{UO.username}}</h2>

    <h2>email is {{UO.email}}</h2>
    <h2>address is {{PO.address}}</h2>
    <img src="{{PO.profile_pic.url}}" alt="" srcset="">
{% endblock %}

templates/seven.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>ON Click</title>
</head>
<body>
    <div>
        <p id="one">0</p>
        <div>
            <button onclick="Inc()">Increase</button>
            <button onclick="Inc()">Reset</button>
            <button onclick="Inc()">Decrement</button>
        </div>
    </div>
</body>
</html>